name: "Armory3D Setup"
description: "Setup Armory3D SDK"
author: "tong <tong@disktree.net>"
runs:
  using: "node12"
  main: "index.js"
inputs:
  blend:
    description: "Main blend file"
    required: true
  publish:
    description: "Publish this export preset"
    required: false
  build:
    description: "Build this export preset"
    required: false
  blender:
    description: "Blender version to use (snap)"
    required: false
    default: 3.3lts/stable
  armsdk_url:
    description: "URL of the armsdk repository"
    required: false
    default: "https://github.com/armory3d/armsdk"
  armsdk_ref:
    description: "Named branch, tag, or SHA of the armsdk repository"
    required: false
    default: main
outputs:
  code:
    description: "Exit code"
  result:
    description: "Process stdout"
  error:
    description: "Process stderr"
  time:
    description: "Build time"
branding:
  icon: "activity"
  color: "red"
