name: 'Armory3D integration'
description: 'Setup armory sdk'
author: 'tong <tong@disktree.net>'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'red'
inputs:
  blend:
    description: 'Main blend file'
    required: false
  blends:
    description: 'Blend files to build'
    required: false
  target:
    description: 'Build target'
    required: false
  targets:
    description: 'Build targets'
    required:  false
  armory_version:
    description: 'Armory version to use'
    required: false
    default: 'master'
  release:
    description: 'Build in release mode'
    default: false
  repository:
    description: 'armsdk repository path'
    required: false
    default: 'https://github.com/armory3d/armsdk'
outputs:
  build-status:
    description: 'The status of the build that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'
