name: "Armory3D Setup"
description: "Setup Armory3D SDK"
author: "tong <tong@disktree.net>"
runs:
  using: "node12"
  main: "index.js"
inputs:
  blend:
    description: "Main blend file"
    required: true
  publish:
    description: "Publish project with this exporter"
    required: false
  build:
    description: "Build project with this exporter"
    required: false
  # renderpath:
  #   description: 'Name of the renderpath preset to use'
  #   required: false
  blender:
    description: "Blender version to use (snap)"
    required: false
    default: latest/stable
  armsdk:
    description: "Armsdk ref to use"
    required: false
    default: "master"
  armsdk_repository:
    description: "Path to the armsdk repository"
    required: false
    default: "https://github.com/armory3d/armsdk"
outputs:
  code:
    description: "Exit code"
  result:
    description: "Build stdout message"
  error:
    description: "Build stderr message"
  time:
    description: "Build time"
branding:
  icon: "activity"
  color: "red"
