name: 'Armory3D Setup'
description: 'Setup Armory3D SDK'
author: 'tong <tong@disktree.net>'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  blend:
    description: 'Main blend file'
    required: true
  exporter:
    description: 'Exporter name'
    required: false
  armsdk_repository:
    description: 'Path to the armsdk repository'
    required: false
    default: 'https://github.com/armory3d/armsdk'
  armory_version:
    description: 'Armory version to use'
    required: false
    default: 'master'
outputs:
  code:
    description: 'Exit code'
branding:
  icon: 'activity'
  color: 'red'
