name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build actions script
        run: |
          npm install
          npm run dist
      # - name: Cache armsdk
      #   uses: actions/cache@v2
      #   env:
      #     armsdk-cache-version: 21.07
      #   with:
      #     path: ./armsdk
      #     key: armsdk-cache-${{ env.armsdk-cache-version }}
      - name: Build
        uses: ./
        with:
          blend: test/empty.blend
      - name: Check build result
        run: |
          tree test/build_empty
          test -f test/khafile.js
          test -f test/Sources/Main.hx
      - name: Export html5
        uses: ./
        with:
          blend: test/empty.blend
          exporter: html5
      - name: Check export result
        run: |
          tree test/build_empty
          test -f test/khafile.js
          test -f test/Sources/Main.hx
          test -f test/build_empty/html5/kha.js
