name: test

on:
  push:
    paths:
      - src/**
      - action.yml
      - package*.json
      - tsconfig.json
      - .github/workflows/test.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run dist
