name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          armory_version: master
          blend: test/empty.blend
          targets: '["html5","krom","linux-hl"]'
          release: false
      - name: Test built files
        run: |
          test -d test/Sources
          test -f test/khafile.js
          test -d test/build_empty
